### ISSUE TITLE
Unable to reproduce PANDORA resluts on RMVP3D-squirrel

### ISSUE THREAD

**Issue by XOURTNEY** [PRIS-CV/NeRSP#3]
Thanks for your amazing dataset!

I try to reproduce the PANDORA resluts on RMVP3D-squirrel, but I got bad outputs. Specifically, I colmap the squirrel dataset and use precess it into PANDORA format. Then I input the stokes like the way NeRSP did. I run 100000 iterations using PANDORA real-owl parameters (I warm up 5000 iteartions by volsdf).

However, the predicted S0 and rgb are all black images. The predicted normals are random. The mesh is a weird cube. I think maybe it's the PANDORA owl's parameters don't fit into the squirrel dataset.

Do you have some idea about this results and how to fix this?

Looking forward to your reply!
![so_rgb](https://github.com/user-attachments/assets/bf09347f-0fcb-48d1-b98d-217bc3b3da6d)
![normal](https://github.com/user-attachments/assets/7e1906cf-6f32-4538-a6c1-0a6273fb98d1)
![mesh_100000](https://github.com/user-attachments/assets/f116b77c-e058-4d26-80e1-34afd5f072af)

**Comment by Yu-fei-Han** [comment]
I think you may not choose the correct config file. Squirrel is in the SMVP3D, not in PANDORA. You should follow README.md to test on 6 images. The difference process of dataset loader between ours and PANDORA can be found in model/dataio/ours_data.py from lines 101-114. So I think you may not load the correct stokes information.

**Comment by XOURTNEY** [comment]
老师不好意思我之前说的有点混乱，我的英语不太好。

我想用松鼠的数据集跑潘多拉，复现NeRSP论文里实验部分潘多拉跑松鼠得到的结果。就是图片里这个蓝圈里的。
![微信截图_20240801140016](https://github.com/user-attachments/assets/1c477798-1549-481e-9d0b-799a1ddd120f)

在我用松鼠的数据集跑潘多拉代码的时候，参数用的是潘多拉缺省的，但是得到了最开始图片混乱的结果，而不是上图蓝圈里的那只。

我该调整一下潘多拉的哪些参数？或者说您当时跑这个结果的时候会考虑调哪些参数？

**Comment by Yu-fei-Han** [comment]
我觉得是相机参数或者图像加载有问题了， 可以不用使用colmap进行相机标定，直接用提供的cameras.npz即可。此外，我已经提供了独立的s0、s1、s2，在数据预处理的时候也不必转换成PANDORA的格式了吧。可以把第一步的gt image打出来看看是不是正确的图像，再检查检查吧。
