### ISSUE TITLE
david on NeRO

### ISSUE THREAD

**Issue by nonAme160** [PRIS-CV/NeRSP#6]
老师好，我在论文里看见您用数据集在其他网络上运行然后对结果做对比
![image](https://github.com/user-attachments/assets/52c4e510-b3d4-460f-9a66-16213d53456e)
，我也尝试在NeRO上复现这个数据集，但是不知道是不是因为图片视角太少了，无法通过colnmap这个环节 报错显示特征匹配失败，请问您当时是如何处理这个情况的？

**Comment by Yu-fei-Han** [comment]
你好，对于SMVP3D这个数据集，可以直接使用给出的camera.npz作为相机参数来进行复现。david这个例子由于是texture less的物体，我猜测这一特点不适用于COLMAP进行二次标定。此外，对于nero这个方法，david这个例子在稀疏视角下无法恢复形状（sparse的视角是可以的），这应该也和no texture有关系。

**Comment by nonAme160** [comment]
> 你好，对于SMVP3D这个数据集，可以直接使用给出的camera.npz作为相机参数来进行复现。david这个例子由于是texture less的物体，我猜测这一特点不适用于COLMAP进行二次标定。此外，对于nero这个方法，david这个例子在稀疏视角下无法恢复形状（sparse的视角是可以的），这应该也和no texture有关系。

因为david这个例子的材质问题，所以可能无法使用COLAMP，但其他稀疏视角的例子是可以用NeRO方法的，只需要使用给出的camera.npz作为相机参数来复现，我的理解对吗？
